### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by Cantusstar** [kriasoft/aspnet-starter-kit#16]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[npm-debug.log.zip](https://github.com/kriasoft/aspnet-starter-kit/files/379080/npm-debug.log.zip)

**Comment by koistya** [comment]
@Cantusstar are you using Node.js v6+?

**Comment by scripni** [comment]
@koistya Hitting the same issue, running node v4.4.7

```
C:\Users\andreisc\Source\Repos\aspnet-starter-kit (master) (app@0.0.0)
λ node run
C:\Users\andreisc\Source\Repos\aspnet-starter-kit\run.js:68
  let count = environments.length;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users\andreisc\Source\Repos\aspnet-starter-kit (master) (app@0.0.0)
λ node --version
v4.4.7
```

**Comment by scripni** [comment]
@koistya @Cantusstar  I took a look at the documentation and saw that node v6.0+ is required for this, works great after updating

**Comment by Cantusstar** [comment]
@koistya @scripni Updating Node worked here as well, Thank you!!
