### ISSUE TITLE
Exception thrown from WebPack

### ISSUE THREAD

**Issue by KenDRhyD** [kriasoft/aspnet-starter-kit#29]
Environment: MacOS 10.11.6

Installed yo and generator-aspnetcore and then created a new project. Ran "npm install".

Opened the project in Visual Code and entered "npm run"in the terminal, and the following was displayed:

bash-3.2$ npm start

> app@0.0.0 start /Users/krallen/Projects/DotNetCore/d2llontario
> node run

Starting 'start'...
Starting 'clean'...
Finished 'clean' after 36ms
Starting 'appsettings'...
Finished 'appsettings' after 4ms
Error
    at webpack (/Users/krallen/Projects/DotNetCore/d2llontario/node_modules/webpack/lib/webpack.js:19:9)
    at resolve (/Users/krallen/Projects/DotNetCore/d2llontario/run.js:159:24)
    at Promise.resolve.then.then.then (/Users/krallen/Projects/DotNetCore/d2llontario/run.js:156:17)
bash-3.2$

Line 19 of the Webpack.js file contains the line:

throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);

This seems to come from the loading of a 'schema' file:

const webpackOptionsSchema = require("../schemas/webpackOptionsSchema.json");

I have not modified anything, so why should this be occurring?

**Comment by MaxSan** [comment]
Exact same issue on 16.04 LTS Ubuntu.

**Comment by robertzas** [comment]
It looks like the yo package is out of date, I got it to work by upgrade all of the npm packages to their latest versions except webpack and history, but then noticed that the update to dotnet core 1.1.0 wasn't included with the yo package either.

Just clone the main branch. I'm working on adding authentication with JWT using identity server 4 on my fork, you can clone that too, just change the database string to your own(I use elephantsql, it's free and easy).

**Comment by KenDRhyD** [comment]
Yes, cloning from the main branch does produce a running system, but not one that actually illustrates retrieving data from the .Net Core server aspect! Still, at least it builds and runs.
